# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('profiles', models.ManyToManyField(related_name='twitter_profile_sets', to='test_app.TwitterProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_content',
            new_name='content_score',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_friend',
            new_name='friend_score',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_network',
            new_name='network_score',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_scores_english',
            new_name='overall_score_english',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_scores_universal',
            new_name='overall_score_universal',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_temporal',
            new_name='temporal_score',
        ),
        migrations.RenameField(
            model_name='botometerscore',
            old_name='botometer_user',
            new_name='user_score',
        ),
        migrations.RemoveField(
            model_name='twitterrelationship',
            name='dates',
        ),
        migrations.AddField(
            model_name='botometerscore',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='twitterrelationship',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twitterrelationship',
            name='run_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltweet',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
