# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botometerscore',
            name='automation_probability_english',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='botometerscore',
            name='automation_probability_universal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='botometerscore',
            name='error',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltweet',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicaltweet',
            name='user_mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), default=[], null=True, size=None),
        ),
    ]
