# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20180717_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltweet',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
    ]
