version: '2.3'
services:
  pewthon:
    container_name: pewthon
    image: 458280294434.dkr.ecr.us-east-1.amazonaws.com/pewthon:2018-05-21
    ports:
      - "8080:8080/tcp"
    volumes:
      #- "${HOME}/.aws:/root/.aws"
      #- "${HOME}/.aws:/home/ec2-user/.aws"
      - "${HOME}/repos:/opt/repos"
    #command: ["tail", "-f", "/dev/null"]
    entrypoint: ["tail", "-f", "/dev/null"]
    #init: true
