# Generated by Django 3.0.2 on 2020-02-20 14:52

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltwitterprofile',
            name='geo_enabled',
        ),
        migrations.RemoveField(
            model_name='historicaltwitterprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='historicaltwitterprofile',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='historicaltwitterprofile',
            name='utc_offset',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='geo_enabled',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='utc_offset',
        ),
    ]
