# Generated by Django 3.1.2 on 2021-06-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20201125_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotometerScore',
        ),
    ]
