# Generated by Django 3.0.2 on 2020-01-14 15:44

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


def migrate_followers(apps, schema_editor):

    for profile in apps.get_model(settings.TWITTER_APP, "TwitterProfile").objects.all():

        for run_id in profile.follower_details.values_list("run_id", flat=True).distinct():
            followers = profile.follower_details.filter(run_id=run_id).order_by("date")
            follower_list = apps.get_model(settings.TWITTER_APP, "TwitterFollowerList").objects.create(
                profile=profile,
                start_time=followers[0].date
            )
            for follower in followers:
                follower_list.followers.add(follower.follower)
            follower_list.finish_time = follower.date
            follower_list.save()


def migrate_followings(apps, schema_editor):

    for profile in apps.get_model(settings.TWITTER_APP, "TwitterProfile").objects.all():

        for run_id in profile.following_details.values_list("run_id", flat=True).distinct():
            followings = profile.following_details.filter(run_id=run_id).order_by("date")
            following_list = apps.get_model(settings.TWITTER_APP, "TwitterFollowingList").objects.create(
                profile=profile,
                start_time=followings[0].date
            )
            for following in followings:
                following_list.followings.add(following.following)
            following_list.finish_time = following.date
            following_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFollowerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterFollowingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_followers),
        migrations.RunPython(migrate_followings),
        migrations.RemoveField(
            model_name='twitterrelationship',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='twitterrelationship',
            name='following',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='followers',
        ),
        migrations.DeleteModel(
            name='HistoricalTwitterProfile',
        ),
        migrations.DeleteModel(
            name='TwitterRelationship',
        ),
        migrations.AddField(
            model_name='twitterfollowinglist',
            name='followings',
            field=models.ManyToManyField(to='testapp.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='twitterfollowinglist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_lists', to='testapp.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='twitterfollowerlist',
            name='followers',
            field=models.ManyToManyField(to='testapp.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='twitterfollowerlist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_lists', to='testapp.TwitterProfile'),
        ),
    ]