# Generated by Django 3.0.2 on 2020-02-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200220_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltwitterprofile',
            name='most_recent_snapshot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testapp.TwitterProfileSnapshot'),
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='most_recent_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.TwitterProfileSnapshot'),
        ),
    ]
